<?php

declare(strict_types=1);

return [
    'version' => '1.3.2',
    'updated_at' => '2026-03-31',
    'matcher' => [
        'normalize' => [
            'trim' => true,
            'lowercase' => true,
            'collapse_spaces' => true,
            'remove_diacritics' => true,
        ],
        'scoring' => [
            'keyword_hit' => 1.0,
            'phrase_hit' => 2.0,
            'regex_hit' => 2.5,
            'entity_hit' => 1.2,
            'priority_weight' => 0.15,
        ],
    ],
    'default_fallback' => [
        'message' => 'Toi chua hieu ro cau hoi. Ban thu hoi theo mau ben duoi.',
        'suggestions' => [
            'Toi muon vao tai khoan',
            'Co mon an it calo khong?',
            'Xem ke hoach bua an o dau?',
        ],
        'suggest_intents' => true,
        'suggest_intent_ids' => ['auth_login', 'recipes_browse', 'diet_weight_loss'],
    ],
    'intents' => [
        [
            'id' => 'auth_login',
            'group' => 'auth',
            'type' => 'route',
            'priority' => 95,
            'keywords' => ['dang nhap', 'login', 'vao tai khoan', 'mo account', 'sign in'],
            'phrases' => ['toi muon vao tai khoan'],
            'route' => ['method' => 'GET', 'path' => '/login'],
            'response' => 'Ban vao trang Dang nhap de truy cap tai khoan.',
        ],
        [
            'id' => 'auth_register',
            'group' => 'auth',
            'type' => 'route',
            'priority' => 90,
            'keywords' => ['dang ky', 'tao tai khoan', 'register', 'sign up'],
            'route' => ['method' => 'GET', 'path' => '/register'],
            'response' => 'Ban vao trang Dang ky de tao tai khoan moi.',
        ],
        [
            'id' => 'auth_forgot_password',
            'group' => 'auth',
            'type' => 'route',
            'priority' => 100,
            'keywords' => ['quen mat khau', 'khoi phuc mat khau', 'reset mat khau'],
            'patterns' => ['/(reset|forgot)\\s*(password|mat khau)/ui'],
            'route' => ['method' => 'GET', 'path' => '/forgot-password'],
            'response' => 'Ban vao trang Quen mat khau de dat lai mat khau.',
        ],
        [
            'id' => 'recipes_browse',
            'group' => 'recipe',
            'type' => 'route',
            'priority' => 70,
            'keywords' => ['xem cong thuc', 'cong thuc', 'mon an'],
            'route' => ['method' => 'GET', 'path' => '/recipes'],
            'response' => 'Ban co the xem danh sach cong thuc tai trang Cong thuc.',
        ],
        [
            'id' => 'recipe_recommend',
            'group' => 'recipe',
            'type' => 'logic',
            'priority' => 90,
            'keywords' => ['an gi', 'goi y mon', 'toi nay an gi', 'hom nay an gi', 'toi co', 'co nguyen lieu', 'cach nau', 'nau mon', 'huong dan nau'],
            'phrases' => ['cach nau mon ga', 'cach nau mon heo', 'cach nau mon bo', 'cach nau mon ca'],
            'patterns' => ['/(cach nau|nau mon|huong dan nau).*(ga|heo|bo|ca|tom|muc|dau hu|rau)/ui'],
            'response' => 'Toi co the goi y mon an phu hop.',
            'suggest_next' => ['Ban muon bua nao?', 'Ban co nguyen lieu gi?'],
            'entities' => [
                'meal' => ['bua sang', 'sang', 'bua trua', 'trua', 'bua toi', 'toi nay'],
                'cooking_method' => ['canh', 'chien', 'xao', 'hap', 'nuong', 'kho'],
                'flavor' => ['cay', 'chua', 'ngot', 'man', 'thanh'],
            ],
        ],
        [
            'id' => 'mealplan_view',
            'group' => 'meal_plan',
            'type' => 'route',
            'priority' => 80,
            'keywords' => ['ke hoach bua an', 'meal plan', 'thuc don tuan'],
            'route' => ['method' => 'GET', 'path' => '/meal-plans'],
            'response' => 'Ban vao trang Lap ke hoach de xem va quan ly thuc don.',
            'requires_login' => true,
        ],
        [
            'id' => 'diet_weight_loss',
            'group' => 'nutrition',
            'type' => 'logic',
            'priority' => 110,
            'keywords' => ['an gi giam can', 'giam can', 'eat clean', 'healthy'],
            'phrases' => ['toi muon giam can nen an gi'],
            'response' => 'Toi co the goi y mon giam can theo bua sang trua toi.',
            'suggest_next' => ['Ban muon bua nao?', 'Ban muon tranh nguyen lieu nao?'],
            'entities' => [
                'meal' => ['bua sang', 'sang', 'bua trua', 'trua', 'bua toi', 'toi nay'],
                'calories' => '\\d+\\s*(kcal|calo)',
                'cooking_method' => ['canh', 'chien', 'xao', 'hap', 'nuong', 'kho'],
                'flavor' => ['cay', 'chua', 'ngot', 'man', 'thanh'],
            ],
        ],
        [
            'id' => 'diet_low_calorie',
            'group' => 'nutrition',
            'type' => 'logic',
            'priority' => 108,
            'keywords' => ['mon it calo', 'it kcal', 'duoi 500 calo', 'kcal'],
            'response' => 'Toi co the goi y mon it calo theo muc kcal ban muon.',
            'suggest_next' => ['Ban muon gioi han bao nhieu kcal?', 'Ban uu tien mon thit hay mon chay?'],
            'entities' => [
                'meal' => ['bua sang', 'sang', 'bua trua', 'trua', 'bua toi', 'toi nay'],
                'calories' => '\\d+\\s*(kcal|calo)',
                'cooking_method' => ['canh', 'chien', 'xao', 'hap', 'nuong', 'kho'],
                'flavor' => ['cay', 'chua', 'ngot', 'man', 'thanh'],
            ],
        ],
        [
            'id' => 'nutrition_recipe_calories',
            'group' => 'nutrition',
            'type' => 'logic',
            'priority' => 109,
            'keywords' => ['mon nay bao nhieu calo', 'bao nhieu calo', 'calo cua mon nay'],
            'response' => 'Toi co the uoc tinh calo cho mon gan nhat ma ban dang xem.',
            'context_keys' => ['last_recipe'],
            'suggest_next' => ['Neu ban muon chinh xac hon, hay gui ten mon cu the.'],
        ],
        [
            'id' => 'profile_view',
            'group' => 'profile',
            'type' => 'route',
            'priority' => 75,
            'keywords' => ['ho so cua toi', 'profile toi', 'trang ca nhan'],
            'route' => ['method' => 'GET', 'path' => '/profile'],
            'response' => 'Ban co the xem ho so tai trang Ho so.',
            'requires_login' => true,
        ],
    ],
];
