from pathlib import Path
files = [
'app/controllers/CommentController.php','app/controllers/IngredientController.php','app/controllers/RecipeController.php','app/controllers/TipsController.php','app/controllers/UserController.php','app/models/RecipeModel.php','app/views/admin/ingredient_detail.php','app/views/admin/manage_banners.php','app/views/admin/manage_bans.php','app/views/admin/manage_categories.php','app/views/admin/manage_ingredients.php','app/views/admin/manage_notifications.php','app/views/admin/manage_recipes.php','app/views/admin/manage_relationships.php','app/views/admin/manage_reports.php','app/views/admin/manage_stats.php','app/views/admin/manage_users.php','app/views/admin/recipe_detail.php','app/views/auth/admin_login.php','app/views/errors/404.php','app/views/ingredients/create.php','app/views/ingredients/index.php','app/views/layouts/admin_header.php','app/views/mealplans/index.php','app/views/partials/ingredient/quick_info_actions_card.php','app/views/partials/shared/comment_report_dropdown.php','app/views/partials/shared/content_action_buttons.php','app/views/partials/shared/content_report_modal.php','app/views/partials/shared/report_content_form.php','app/views/recipes/show.php','app/views/recipes/partials/quick_actions.php','app/views/recipes/partials/report_modal.php','app/views/tips/index.php','app/views/tips/show.php','app/views/user/connections.php','app/views/user/profile.php'
]
replacements = {
'B?n dang b? khóa quyền bình luận đến ': 'Bạn đang bị khóa quyền bình luận đến ',
'B?n dang b? khóa quyền bình luận vĩnh viễn. Lý do: ': 'Bạn đang bị khóa quyền bình luận vĩnh viễn. Lý do: ',
'B?n đang bị khóa quyền bình luận đến ': 'Bạn đang bị khóa quyền bình luận đến ',
'B?n đang bị khóa quyền bình luận vĩnh viễn. Lý do: ': 'Bạn đang bị khóa quyền bình luận vĩnh viễn. Lý do: ',
'Không thể đăng bình luận': 'Không thể đăng bình luận',
'Nội dung không phù hợp': 'Nội dung không phù hợp',
'Có báo cáo bình luận mới': 'Có báo cáo bình luận mới',
'Nguyn li?u': 'Nguyên liệu',
'Không tìm thấy nguyên liệu.': 'Không tìm thấy nguyên liệu.',
'Vui lòng nhập tên nguyên liệu.': 'Vui lòng nhập tên nguyên liệu.',
'Không thể gửi nguyên liệu.': 'Không thể gửi nguyên liệu.',
'Tên nguyên liệu đang bị ràng buộc UNIQUE trong CSDL. Vui lòng xóa UNIQUE ở cột name.': 'Tên nguyên liệu đang bị ràng buộc UNIQUE trong CSDL. Vui lòng xóa UNIQUE ở cột name.',
'Góp ý nguyên liệu': 'Góp ý nguyên liệu',
'Nguyên liệu của tôi': 'Nguyên liệu của tôi',
'Nội dung nguyên liệu có dấu hiệu vi phạm.': 'Nội dung nguyên liệu có dấu hiệu vi phạm.',
'Có báo cáo nguyên liệu mới (ID: ': 'Có báo cáo nguyên liệu mới (ID: ',
'Đã gửi báo cáo nguyên liệu.': 'Đã gửi báo cáo nguyên liệu.',
'Bạn đã báo cáo nguyên liệu này.': 'Bạn đã báo cáo nguyên liệu này.',
'Bạn đang bị khóa đăng nguyên liệu đến ': 'Bạn đang bị khóa đăng nguyên liệu đến ',
'Bạn đang bị khóa đăng nguyên liệu vĩnh viễn. Lý do: ': 'Bạn đang bị khóa đăng nguyên liệu vĩnh viễn. Lý do: ',
'Không tìm thấy mẹo vặt.': 'Không tìm thấy mẹo vặt.',
'Vui lòng nhập đầy đủ tiêu đề và nội dung.': 'Vui lòng nhập đầy đủ tiêu đề và nội dung.',
'Không thể gửi mẹo vặt.': 'Không thể gửi mẹo vặt.',
'Góp ý mẹo vặt': 'Góp ý mẹo vặt',
'Mẹo vặt của tôi': 'Mẹo vặt của tôi',
'Nội dung mẹo vặt có dấu hiệu vi phạm.': 'Nội dung mẹo vặt có dấu hiệu vi phạm.',
'Có báo cáo mẹo vặt mới (ID: ': 'Có báo cáo mẹo vặt mới (ID: ',
'Đã gửi báo cáo mẹo vặt.': 'Đã gửi báo cáo mẹo vặt.',
'Bạn đã báo cáo mẹo vặt này.': 'Bạn đã báo cáo mẹo vặt này.',
'Bạn đang bị khóa đăng mẹo đến ': 'Bạn đang bị khóa đăng mẹo đến ',
'Bạn đang bị khóa đăng mẹo vĩnh viễn. Lý do: ': 'Bạn đang bị khóa đăng mẹo vĩnh viễn. Lý do: ',
'Không tìm thấy công thức.': 'Không tìm thấy công thức.',
'Vui lòng nhập tiêu đề và mô tả.': 'Vui lòng nhập tiêu đề và mô tả.',
'Không thể tạo công thức.': 'Không thể tạo công thức.',
'Đăng công thức': 'Đăng công thức',
'Đã lưu': 'Đã lưu',
'Không thể cập nhật.': 'Không thể cập nhật.',
'Đã lưu công thức.': 'Đã lưu công thức.',
'Đã bỏ lưu công thức.': 'Đã bỏ lưu công thức.',
'Vui lòng nhập lý do.': 'Vui lòng nhập lý do.',
'Bạn đã báo cáo công thức này.': 'Bạn đã báo cáo công thức này.',
'Có báo cáo công thức mới (ID: ': 'Có báo cáo công thức mới (ID: ',
'Không thể theo dõi.': 'Không thể theo dõi.',
'Tài khoản đang bị khóa theo dõi tạm thời.': 'Tài khoản đang bị khóa theo dõi tạm thời.',
'đã theo dõi bạn.': 'đã theo dõi bạn.',
'Đã theo dõi.': 'Đã theo dõi.',
'Đã hủy theo dõi.': 'Đã hủy theo dõi.',
'Đã đăng': 'Đã đăng',
'Hoàn thiện': 'Hoàn thiện',
'Nhập': 'Nhập',
'Bạn đang bị khóa đăng bài đến ': 'Bạn đang bị khóa đăng bài đến ',
'Bạn đang bị khóa đăng bài vĩnh viễn. Lý do: ': 'Bạn đang bị khóa đăng bài vĩnh viễn. Lý do: ',
'Admin không cần thấy bài nháp.': 'Admin không cần thấy bài nháp.',
'Bài đã gửi duyệt thường có user_state="completed", vẫn phải hiện cho admin duyệt.': 'Bài đã gửi duyệt thường có user_state="completed", vẫn phải hiện cho admin duyệt.',
'Đã duyệt': 'Đã duyệt',
'Chi tiết nguyên liệu': 'Chi tiết nguyên liệu',
'Chưa phân loại': 'Chưa phân loại',
'Từ chối nguyên liệu này?': 'Từ chối nguyên liệu này?',
'Mô tả': 'Mô tả',
'Công dụng': 'Công dụng',
'Cách sơ chế': 'Cách sơ chế',
'Cách bảo quản': 'Cách bảo quản',
'Đang cập nhật.': 'Đang cập nhật.',
'Đã cập nhật công thức nổi bật.': 'Đã cập nhật công thức nổi bật.',
'Đã cập nhật công thức hôm nay.': 'Đã cập nhật công thức hôm nay.',
'Lưu công thức hôm nay thất bại.': 'Lưu công thức hôm nay thất bại.',
'Đang chọn cho ': 'Đang chọn cho ',
'Đã gỡ ban thành công.': 'Đã gỡ ban thành công.',
'Không thể gỡ ban. Vui lòng thử lại.': 'Không thể gỡ ban. Vui lòng thử lại.',
'Danh sách ban': 'Danh sách ban',
'Theo dõi và gỡ các hình thức ban/khóa hiện hành.': 'Theo dõi và gỡ các hình thức ban/khóa hiện hành.',
'Khóa': 'Khóa',
'Tất cả': 'Tất cả',
'Quản lí danh mục': 'Quản lí danh mục',
'Tổ chức nhằm món ăn và bộ sưu tập.': 'Tổ chức nhằm món ăn và bộ sưu tập.',
'Danh sách danh mục': 'Danh sách danh mục',
'Thêm danh mục': 'Thêm danh mục',
'Không tìm thấy danh mục nào.': 'Không tìm thấy danh mục nào.',
'Vui lòng nhập tên nguyên liệu.': 'Vui lòng nhập tên nguyên liệu.',
'Không thể lưu nguyên liệu. Vui lòng thử lại.': 'Không thể lưu nguyên liệu. Vui lòng thử lại.',
'Thư viện nguyên liệu': 'Thư viện nguyên liệu',
'Admin có thể tạo, sửa, xóa. Người dùng gửi nguyên liệu sẽ ở trạng thái chờ duyệt.': 'Admin có thể tạo, sửa, xóa. Người dùng gửi nguyên liệu sẽ ở trạng thái chờ duyệt.',
'Để thêm nguyên liệu mới.': 'Để thêm nguyên liệu mới.',
'Thêm nguyên liệu (Admin)': 'Thêm nguyên liệu (Admin)',
'Thêm mới': 'Thêm mới',
'Tên nguyên liệu *': 'Tên nguyên liệu *',
'Mô tả': 'Mô tả',
'Công dụng': 'Công dụng',
'Hình ảnh': 'Hình ảnh',
'Lưu nguyên liệu': 'Lưu nguyên liệu',
'Danh sách nguyên liệu': 'Danh sách nguyên liệu',
'Chưa có nguyên liệu nào.': 'Chưa có nguyên liệu nào.',
'Đã duyệt': 'Đã duyệt',
'Thêm mới': 'Thêm mới',
'Tiêu đề *': 'Tiêu đề *',
'Mô tả *': 'Mô tả *',
'Thời gian nấu (phút)': 'Thời gian nấu (phút)',
'Độ khó': 'Độ khó',
'Khó': 'Khó',
'Hình ảnh': 'Hình ảnh',
'Lưu công thức': 'Lưu công thức',
'Đã thêm công thức mới.': 'Đã thêm công thức mới.',
'Danh sách công thức': 'Danh sách công thức',
'Không có công thức nào đang chờ duyệt.': 'Không có công thức nào đang chờ duyệt.',
'Tiêu đề': 'Tiêu đề',
'Tác giả': 'Tác giả',
'Trạng thái': 'Trạng thái',
'Hành động': 'Hành động',
'Quản lí mối quan hệ': 'Quản lí mối quan hệ',
'Giám sát follow giữa người dùng và xử lý vi phạm khi cần.': 'Giám sát follow giữa người dùng và xử lý vi phạm khi cần.',
'Tìm theo tên/email người theo dõi hoặc được theo dõi': 'Tìm theo tên/email người theo dõi hoặc được theo dõi',
'Vai trò: Tất cả': 'Vai trò: Tất cả',
'User là người theo dõi': 'User là người theo dõi',
'User là người được theo dõi': 'User là người được theo dõi',
'Ngày tạo': 'Ngày tạo',
'Thao tác': 'Thao tác',
'Chưa có dữ liệu mối quan hệ.': 'Chưa có dữ liệu mối quan hệ.',
'Bình thường': 'Bình thường',
'Đang khóa follow': 'Đang khóa follow',
'Mở khóa': 'Mở khóa',
'Khóa 7 ngày': 'Khóa 7 ngày',
'Khóa vĩnh viễn': 'Khóa vĩnh viễn',
'Không có quyền xử lý': 'Không có quyền xử lý',
'Báo cáo vi phạm': 'Báo cáo vi phạm',
'Quản lí chung báo cáo bài đăng và bình luận trong một màn hình.': 'Quản lí chung báo cáo bài đăng và bình luận trong một màn hình.',
'Tìm theo tiêu đề, lí do, người báo cáo': 'Tìm theo tiêu đề, lí do, người báo cáo',
'Đang xem': 'Đang xem',
'Đã xử lý': 'Đã xử lý',
'Tiêu đề': 'Tiêu đề',
'Nội dung bình luận': 'Nội dung bình luận',
'Chưa có báo cáo phù hợp bộ lọc.': 'Chưa có báo cáo phù hợp bộ lọc.',
'Quản lí người dùng': 'Quản lí người dùng',
'Ban, xóa mềm, khôi phục tài khoản kèm tìm kiếm, lọc và phân trang.': 'Ban, xóa mềm, khôi phục tài khoản kèm tìm kiếm, lọc và phân trang.',
'Thao tác thành công.': 'Thao tác thành công.',
'Xóa mềm tài khoản này?': 'Xóa mềm tài khoản này?',
'Khôi phục': 'Khôi phục',
'Xóa mềm': 'Xóa mềm',
'Chi tiết công thức': 'Chi tiết công thức',
'Các bước': 'Các bước',
'Chưa có bước thực hiện.': 'Chưa có bước thực hiện.',
'Vui lòng xác thực tài khoản admin.': 'Vui lòng xác thực tài khoản admin.',
'404 - Không tìm thấy trang': '404 - Không tìm thấy trang',
'Trang bạn tìm không tồn tại.': 'Trang bạn tìm không tồn tại.',
'Góp ý nguyên liệu mới': 'Góp ý nguyên liệu mới',
'Nguyên liệu sẽ ở trạng thái chờ duyệt trước khi hiện thị cho mọi người.': 'Nguyên liệu sẽ ở trạng thái chờ duyệt trước khi hiện thị cho mọi người.',
'Cảm ơn bạn! Nguyên liệu đã được gửi và đang chờ duyệt.': 'Cảm ơn bạn! Nguyên liệu đã được gửi và đang chờ duyệt.',
'Chưa có nguyên liệu được duyệt.': 'Chưa có nguyên liệu được duyệt.',
'Mô tả đang được cập nhật.': 'Mô tả đang được cập nhật.',
'Đăng xuất': 'Đăng xuất',
'Tìm công thức, người dùng...': 'Tìm công thức, người dùng...',
'Bữa sáng': 'Bữa sáng',
'Bữa trưa': 'Bữa trưa',
'Bữa tối': 'Bữa tối',
'Đang khóa': 'Đang khóa',
'Đang mở': 'Đang mở',
'Xóa': 'Xóa',
'Chọn ô trước': 'Chọn ô trước',
}
common_replacements = {
'Khng': 'Không',
'Nguyn': 'Nguyên',
'li?u': 'liệu',
'Qu?n': 'Quản',
'l': 'lí',
'đ?ng': 'đang',
'c': 'có',
'Chua': 'Chưa',
'cA': 'cá',
'cAng': 'công',
'TAc': 'Tác',
'c?': 'của',
'ang': 'Đang',
'': 'Đ',
'?': 'Đ',
'XAc': 'Xác',
'Hon': 'Hoàn',
'Nh?p': 'Nhập',
'Khc': 'Khác',
'Chn': 'Chọn',
'u': 'Đu',
'a': 'Đã',
}
changed_files = []
for file_name in files:
    path = Path(file_name)
    if not path.exists():
        print(f"MISSING: {file_name}")
        continue
    content = path.read_text(encoding='utf-8')
    original = content
    for old, new in replacements.items():
        content = content.replace(old, new)
    for old, new in common_replacements.items():
        content = content.replace(old, new)
    if content != original:
        path.write_text(content, encoding='utf-8')
        changed_files.append(file_name)
        print(f'Updated {file_name}')
print(f'Finished. Updated {len(changed_files)} files.')
